Add option to enable
tox-dev/tox-ansible pull request #87
Opened 2021-04-16 04:51 UTC by greg-hellings

Add an option to enable running tox-ansible, so that it does not distrub
default executions

Fixes #40
Fixes #76

2021-04-19 06:31 UTC, ssbarnea commented
I do not think this is needed. Think about how pytest plugin work, installing them activates them, no extra action needed.

Still, I do think that we could add an option to disable a plugin. Pytest does that too, so you can define which plugins not to load.

The number of people being affected by undesired plugin side-effects is likely very small (probably counting me and you). I would rather improve the plugin logic first to lower the mistakes it does.

Note: optional disable would require less changes, I do not want to add a change that requires you to edit tox.ini in two places for all users if tox-ansible, mentioning the plugin in tox requires key should be enough.

2021-04-19 18:23 UTC, greg-hellings commented
Ah, I only leverage the requires key in my CI environment. I have tox-ansible installed in my normal virtualenv, so it sometimes bites me when I'm working on non-Ansible systems. We can make this one into an optional disable, instead. But it might not be that useful as you note.

I'm open to further suggestions on improving detection. The best seems to be looking for a `galaxy.yml` file in either `$CWD` or `toxinidir`. I don't want to rely on any external tools, like git, because I don't want to hamper the ability to run it outside of a checkout structure or the like. I think the already existing ignore path option should already cover the vast set of scenarios. We might improve that with a default list, like `{toxworkdir}`, which we know could cause problems with detection.

2021-04-20 09:40 UTC, ssbarnea commented
Looking for `galaxy.yml` or `requirements.yml` or `ansible.cfg` inside CWD should be enough for most people. Only `galaxy.yml` is problematic as I am aware of many that have some kind of phobia about anything with galaxy in their name. If they want to declare a repository as an ansible repository but without a galaxy file in the root, they can create an empty requirements.yml file and live with that.

2021-04-22 09:01 UTC, ssbarnea requested changes
Please make it "optional disable" as tox does not have this feature yet and we are good to go.

2021-05-17 08:00 UTC, ssbarnea commented
@greg-hellings Any chance to rework this as an option to disable it?

2021-07-06 10:03 UTC, ssbarnea commented
@greg-hellings Can you please rebase?

2021-08-31 15:57 UTC, ssbarnea approved these changes

2021-09-03 16:49 UTC, merged